### ISSUE TITLE
Strings should be filtered by Source too

### ISSUE THREAD

**Issue by alinaKh** [remuslazar/osx-xliff-tool#1]
When I use filter, it only searches in target column but not in the Source.
I didn't test if the filter works on Note.
I copy translation strings from the huge .xlsx file and desperately need full keyword search
Great tool otherwise. Thank you.

**Comment by remuslazar** [comment]
@alinaKh, thank you for the bug-report and.. yes, you're right, the filter should also search in the source column, I will fix that.

**Comment by alinaKh** [comment]
XliffFile.swift line 44:
   for elementName in ["**original**", "target", "note"] {
replace with:
   for elementName in ["**source**", "target", "note"] {
