### ISSUE TITLE
app crashes on exit

### ISSUE THREAD

**Issue by SimplGy** [remuslazar/osx-xliff-tool#10]
On commit https://github.com/remuslazar/osx-xliff-tool/commit/51d300e579b440fd9a31ee3f9c81c24448b805b9

When I close the window or the app get this crash:

![image](https://cloud.githubusercontent.com/assets/548809/19866762/ff95ff90-9f66-11e6-913e-21d1e9a236cc.png)

Maybe this is a user/developer certificate rights issue?

**Comment by SimplGy** [comment]
This avoids the crash:

```
xliffFile?.files.forEach { outlineView?.expandItem($0) }
```

But there's probably a root cause here I'm missing.

**Comment by SimplGy** [comment]
I am still unable to save, or duplicate and see any of the changes I've made. I think I have the necessary capability enabled.

![image](https://cloud.githubusercontent.com/assets/548809/19867052/45673e7a-9f68-11e6-94c5-06b79c2cca6e.png)

I am probably missing something obvious though because I've never done an OSX app before.

**Comment by remuslazar** [comment]
@SimplGy oh.. the force unwrapping is causing the bug, I will check and fix that, thanks!

**Comment by SimplGy** [comment]
It's two separate things I think, I shouldn't have combined them in one issue. The no-save issue is a non-crashing exception, looks like from line 117 of ViewController.swift:

    2016-10-31 14:22:00.275 XLIFFTool[5797:1088498] -[_SwiftValue updateTranslationForElement:newValue:]: unrecognized selector sent to instance 0x60800009fcc0
