### ISSUE TITLE
Support `Cmd+A` in text field to select all

### ISSUE THREAD

**Issue by SimplGy** [remuslazar/osx-xliff-tool#13]
Would be nice to be able to do this to just re-write all the text in the field.

![image](https://cloud.githubusercontent.com/assets/548809/19871029/c18256f6-9f78-11e6-9dd9-f921e60a7b45.png)

**Comment by remuslazar** [comment]
.. you could just use the BS (backspace) key with the specific row selected (in non-editing mode). This will basically wipe out the translation entirely (setting it to nil). Then press enter and enter the new text.

**Comment by SimplGy** [comment]
The backspace key is good to know about.

The same Cmd+A shortcut is great in the search field too, since as you backspace chars it searches, and that gets a bit laggy the fewer chars there are because there are more results.

I guess there's a clear "X" there but I'm not going to mouse (!). Maybe there's a keyboard shortcut for clear I don't know about?

I'm just used to Cmd+A working everywhere :)
