### ISSUE TITLE
Whitespace being collapsed in `target` output

### ISSUE THREAD

**Issue by SimplGy** [remuslazar/osx-xliff-tool#16]
The text field supports entry of whitespace and displays it correctly:

![image](https://cloud.githubusercontent.com/assets/548809/19873262/aaefeee8-9f83-11e6-9379-6cd6ec7898fd.png)

But the xml output collapses whitespace inside the target node:

![image](https://cloud.githubusercontent.com/assets/548809/19873288/c71aaacc-9f83-11e6-946f-b8a9778b81a7.png)

**Comment by SimplGy** [comment]
But only sometimes?!

![image](https://cloud.githubusercontent.com/assets/548809/19873391/5cbc5a80-9f84-11e6-9ef2-e1835c86941d.png)

Only with punctuation? Let me figure this out here, something funny is going on...

**Comment by remuslazar** [comment]
@SimplGy Using alt-enter works here. Entering a multiline target leads to:

```
        <target>First Line
Second Line
Third Line
4. Line</target>
```

Using ctrl-enter leads to a `<U+2028>` char instead of the regular new line, though.

**Comment by SimplGy** [comment]
That's it. That will confuse the pants off me and I can't stop a translator from doing it, can I?

**Comment by SimplGy** [comment]
Would you take a PR that regex subs `<U+2028>` with the correct newline char whenever the target is saved?

**Comment by remuslazar** [comment]
maybe some fancy post-processing of the entered text will be a solution, I will think about it while implementing #4

**Comment by SimplGy** [comment]
Yep, that's a great idea!

**Comment by SimplGy** [comment]
I've actually not found any suitable tool that can import xliff xml with _either_ literal newlines or `\n` newlines, so after a day of nonsense and frustration around this tiny issue, I've decided all newlines will be represented as an array of localized strings that are `joined(separator: "\n\n")`. I just could not find tooling that could get the import done without manual find and replacing.

As a result, this issue is probably super low priority, even closable, until Xcode fixes one or both of these issues:
- http://www.openradar.me/23410520
- http://www.openradar.me/23410569

**Comment by remuslazar** [comment]
@SimplGy 1fa42de0c5e6ce078f24f4bfde91dd0f1d93bab4 should also resolve this issue, see commit msg.

**Comment by SimplGy** [comment]
Awesome, thanks man!
