### ISSUE TITLE
Crash on startup (edge build)

### ISSUE THREAD

**Issue by SimplGy** [remuslazar/osx-xliff-tool#17]
Using develop latest commit https://github.com/remuslazar/osx-xliff-tool/commit/0882237a093885a54a78583a956db72b89f94b51, The application crashes on startup for me.

I'm thinking you don't see the same issue or else you'd have found it already.

Basically, no matter what file I open, it crashes as soon as I:

* hover a row
* try to use the arrow keys to expand a row
* uncheck "Only non-translated"

I can't get a meaningful error message out of it though, just BAD_ACCESS.

![image](https://cloud.githubusercontent.com/assets/548809/19936792/75459808-a0e4-11e6-93e8-9ab717f6e507.png)

I've tried:

* de.xliff, bigFile.xliff, and myFile.xliff
* Clean build
* System restart
* Setting an exception breakpoint (no further detail during the crash)

If I revert to https://github.com/remuslazar/osx-xliff-tool/commit/d22642b3fb2559150b60451024cadfb30855089b I don't have this crash

**Comment by remuslazar** [comment]
@SimplGy in your stack trace, which objc method is called in frame 1?

**Comment by SimplGy** [comment]
Is each 0-12 item listed under "Thread 1" called a "frame"? Not being coy, this type of development is just new to me.

If so, the method is `ViewController.outlineView(NSOutlineView, isGroupItem: Any) -> Bool`

![image](https://cloud.githubusercontent.com/assets/548809/19938974/95bb3504-a0ec-11e6-9e8c-0c90c57cd886.png)

But on the right hand side it's just assembly:

![image](https://cloud.githubusercontent.com/assets/548809/19938987/a3cd55a0-a0ec-11e6-904d-28fd7eb3befb.png)

**Comment by SimplGy** [comment]
I've had issues in the past with outlets not being ready when I try to use them (for instance, if a presenting VC tries to render because data is available, but the presented VC has not yet called viewWillAppear).

So, I tried making this an optional reference (and fixing all downstream errors that resulted), but got the same crashing behavior. This does not solve the problem, maybe that's useful to know:

```
@IBOutlet weak var outlineView: NSOutlineView?
```

**Comment by remuslazar** [comment]
could u try by 1.2 build here? https://github.com/remuslazar/osx-xliff-tool/releases/tag/1.2 it that works? I Also supplied a valid xliff file for testing.

**Comment by SimplGy** [comment]
That's commit 0882237a093885a54a78583a956db72b89f94b51, it's what I'm using. Also tried de.xliff and the new bigFile.xliff. Or do you mean I should use the binary you built?

**Comment by remuslazar** [comment]
@SimplGy yes, I mean the binary I just uploaded there

**Comment by SimplGy** [comment]
Same crash using your binary:

![image](https://cloud.githubusercontent.com/assets/548809/19939360/3e179fac-a0ee-11e6-9a1c-87b1f11600e0.png)

**Comment by SimplGy** [comment]
OS Version?

![image](https://cloud.githubusercontent.com/assets/548809/19939369/50ad8ee2-a0ee-11e6-8170-6f6c599758b2.png)

**Comment by remuslazar** [comment]
@SimplGy weird.. Sierra 10.12.1 here. Deployment Target is 10.10, though, so theoretically it should not be an issue.

**Comment by remuslazar** [comment]
@SimplGy regarding the implicitly unwrapped (!) optionals: AFAIK they are the same as strong optionals (?), so you can use constructs like `myOutlet?.doSomething()` for both types of optionals. Under the hood they are exactly the same thing, the ! does add some syntactic sugar to the code and make things clearer.

**Comment by remuslazar** [comment]
@SimplGy I am also not very familiar with lldb and  debugging, but there are some really awesome WWDC sessions out there, e.g. https://developer.apple.com/videos/play/wwdc2016/417/. The section about low level debugging is really amazing! Check it out.

**Comment by SimplGy** [comment]
Re: `!/?`:

Sure thing! But if we're getting a bad access and I want to test if that's the cause, I wanted the compiler to help me track down all instances of implicit access.

Re: low-level debugging:

Thanks! I'll watch that with lunch today.

**Comment by remuslazar** [comment]
@SimplGy got ya! I thought you meant that in general it is safer to use strong optionals instead of implicitly unwrapped ones in such cases.

**Comment by remuslazar** [comment]
@SimplGy could u please test e5b1792fffeae129c7bd41dbdab548e24952d531, to see if that fixes the crash issue? I think, using value types is kinda problematic in older Swift runtimes for e.g. El Capitan. Also the NSOutlineView, being a quite old Cocoa API could have problems using value types.

I just created a "testing" branch for that purpose.

**Comment by remuslazar** [comment]
@SimplGy so then.. I just refactored the whole filter handling code to be more efficient and simple, see 41cf532280ff39b1a36bfeb7e2ea89a3d3cf058b. Could u test please against the testing branch? I have a quite good feeling that this will solve this weird issue.. thank you!

**Comment by SimplGy** [comment]
Sure, I'll check it tomorrow! +1 on the better search perf. Should be no problem searching 3000 or so nodes now :)

**Comment by SimplGy** [comment]
I am wondering about value types lately. We have some very strange and intermittent crashes in our iOS app that sort of point in that direction. Wonder if that's a root cause...

**Comment by SimplGy** [comment]
Nevermind tested it today. 41cf532280ff39b1a36bfeb7e2ea89a3d3cf058b works great.

I still get `unrecognized selector sent to instance` when I try to save unless I comment out the undo manager bit, but that's covered by #12.
