### ISSUE TITLE
Support for CSV import and compare source & replace target.

### ISSUE THREAD

**Issue by anuragfluke** [remuslazar/osx-xliff-tool#19]
Hi guys,

I love your good work..It is awesome.. I am searching a solution with xls file which contains language translations. We can generate a csv or plist file with the key and translation strings from xls file with particular language. then we can write a logic for  if key from csv/plist file is equal with source tag in xliff file then we modify value of target tag in xliff file and save xliff.

Can we compare source tag and replace the target with new language? 

@remuslazar

**Comment by remuslazar** [comment]
@anuragfluke this tool is quite specific:

> This is an OS X Application for editing XLIFF files generated by Xcode (Menu Editor > Export for localization...)

For your needs there should be other (more general purpose) tools out there.

I don't plan to add any Excel/CSV/.. support for this app, sorry!
