### ISSUE TITLE
Editing and Saving the file removes all indent

### ISSUE THREAD

**Issue by pappalar** [remuslazar/osx-xliff-tool#2]
After opening a xliff file in Xliff tool

(which looks like this)

`<header>`
`<tool tool-id="com.apple.dt.xcode" tool-name="Xcode" tool-version="7.3.1" build-num="7D1014"/>`
`</header>`
`<body/>`

I edit one line and save.
The file is modified by removing all indents

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 http://docs.oasis-open.org/xliff/v1.2/os/xliff-core-1.2-strict.xsd"><file original="LaunchScreen.xib" source-language="en" datatype="plaintext" target-language="de-DE"><header><tool tool-id="com.apple.dt.xcode" tool-name="Xcode" tool-version="7.3.1" build-num="7D1014"></tool></header><`

I don't think the tool should remove all indents as Xliff are made also to be XML/Human readable and it is pretty inconvenient to have to change it again to check some internal details

**Comment by SimplGy** [comment]
Awesome! Looking forward to using this in the release version. In fact I'm gonna build myself so I can get this feature.
