### ISSUE TITLE
Ability to add new entry

### ISSUE THREAD

**Issue by hoffereka** [remuslazar/osx-xliff-tool#22]
Is it possible? I couldn't find how to add new translation key and translated text pairs to an xliff file. It would be nice because in some circumstances Symfony's export tool does not export all translatable texts into the xlf file.

**Comment by remuslazar** [comment]
no, sorry, this tool is not general purpose, it serves a very specific need while using X-Code.

**Comment by hoffereka** [comment]
would You merge if I implement it in a pull request?

**Comment by remuslazar** [comment]
no, sorry, I don't have any plans to make it GP, I want to keep it simple and focused :/
