### ISSUE TITLE
allow open .xml files

### ISSUE THREAD

**Issue by b2un0** [remuslazar/osx-xliff-tool#25]
we have xliff translations as `.xml` files - how to open this files?

if i rename our files from `.xml` to `.xliff` everything works, but this not a good workflow for us.

can you please add an option to allow `.xml` files?

**Comment by remuslazar** [comment]
@b2un0: this tool has been built to serve a very specific need:

> This is an OS X Application for editing XLIFF files generated by Xcode (Menu Editor > Export for localization...)

For your needs there should be other (more general purpose) tools out there. sorry
