### ISSUE TITLE
Allow Copying the Source

### ISSUE THREAD

**Issue by ArturoLee** [remuslazar/osx-xliff-tool#40]
I love this tool! Only one improvement I would make. Since I do the translation, a lot of times I have to search up the translation on google translate. It would be very convenient if it would let me copy the source content so I can then paste it. Right now I have to manually type it out. 

Thanks!

**Comment by remuslazar** [comment]
@ArturoLee you could press "CMD + ALT + C" to copy the content from source to destination (see the associated menu item), then double click to select it, then as usual CMD +C to copy it to the clipboard and move on.

That's the way I'm doing that kind of tasks.

**Comment by ArturoLee** [comment]
@remuslazar That is great! That does make it much more faster. Still, if there was a way to instantly clipboard it, that would be awesome. But anyway, you literally saved me so much time. Thank you!
