### ISSUE TITLE
Handle multi-line strings

### ISSUE THREAD

**Issue by SimplGy** [remuslazar/osx-xliff-tool#8]
This is a pain point with the xcode import as well.

It appears this tool does not identify or display multi line strings.

Screenshot:

![image](https://cloud.githubusercontent.com/assets/548809/19864314/512a5a36-9f5d-11e6-97b2-79d603f56f29.png)

eg: 

    <trans-unit id="Help-contactingRestaurant-body">
      <source>We're contacting the restaurant now.

      When we know how long the restaurant needs to prep your order, we'll let you know. We'll send you a notification when your food is ready, too.</source>
      <note>Help-contactingRestaurant-body: Body text for this help section</note>
    </trans-unit>

(That blank line is intentional, so it looks like a paragraph separation in the display)

This tool is the best I've found and I think the community could really use a free xliff tool. The other ones are $10-20.

I can give you a hand with this if you'll help me get started--want to point me to the right part of the code?

**Comment by remuslazar** [comment]
@SimplGy ok, got it! I will try to reproduce the issue and fix it. Stay tuned..

**Comment by SimplGy** [comment]
My fault. It appears to read them fine:

![image](https://cloud.githubusercontent.com/assets/548809/19864506/33a05654-9f5e-11e6-8228-16eb9b7ea67a.png)

Because this option was off by default and I was unware, I thought it was failing to parse.

ideas:
- ignore, user error
- show `...` or similar for truncated strings
- don't have the option on by default

**Comment by SimplGy** [comment]
Hmm... I can't figure out how to enter multiple lines of text in the entry field. I've tried `return` (which saves) and `shift+return`. Oh! `alt+return` does it.

Do you think it would be better to add `shift+return` as well? I think that's the standard, though I don't see any downside to having `alt+return` too.
