### ISSUE TITLE
Collapsing intentional whitespace in base translation turns into `No Translation`

### ISSUE THREAD

**Issue by SimplGy** [remuslazar/osx-xliff-tool#9]
Collapses intentional whitespace in base translation and treats it as "no translation".

This breaks some use cases where you actually intend a blank string, eg:

* Navigation Item with a single blank space is the only (?) way to get a back arrow with no text. A nil or actual blank string will fill in default text.
* UISegmented controls that you want to have empty to start with, but fill in when data loads. A nil would use default text, rather than not having any text at all.

This is probably related to #2. I'll test against the master branch and close this issue if so.

Example. Blank source string turns into "no translation":

![image](https://cloud.githubusercontent.com/assets/548809/19865784/3c4285f2-9f63-11e6-9e9e-59fd34a586f7.png)

**Comment by remuslazar** [comment]
@SimplGy use the develop branch, this is also the default branch right now. I will merge everything into master after the 1.2 release. Soon.

**Comment by SimplGy** [comment]
Ok, thanks. You're on gitflow huh? :)

**Comment by remuslazar** [comment]
sure, gitflow rules:)
